import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas} from '@react-three/fiber';
import {Character} from './Characters';
import {MansafPlatter} from './MansafPlatter';
import {Majlis} from './Majlis';
import {RoomReflections} from './RoomReflections';
import {Portrait} from './Portrait';
import {PlayerHand} from './PlayerHand';
import {freshLokma,lokmaLabel,lokmaScore,type Lokma} from './lokma';
import { botSeats, platterFood } from './platterFood';
import { foodSurface } from './MansafPlatter';
import './style.css';
import './photo.css';
const NAMES=['You','Zaid','Omar','Sami'];
const COLORS=['#e5b75d','#e67a65','#7bb6bb','#a4b57d'];
export type Game={phase:'ready'|'playing'|'ended';remaining:number;scores:number[];eaten:number[];time:number;lokma:Lokma;feedback:string;feedbackAt:number;bites:number[];started:number;nextBots:number[];biteTargets:[number,number,number][];reason:string};
const wait=(i:number)=>[1300,1900,2600][i]+Math.random()*700;
const initial=():Game=>({phase:'ready',remaining:100,scores:[0,0,0,0],eaten:[0,0,0,0],time:30,lokma:freshLokma(),feedback:'',feedbackAt:0,bites:[0,0,0,0],started:0,nextBots:[0,0,0],biteTargets:[[0,0,0],[0,0,0],[0,0,0],[0,0,0]],reason:''});
function finish(g:Game,reason:string){g.phase='ended';g.reason=reason;g.lokma.gathering=false;g.lokma.space=false;}
function Scene({game,remaining,onEat}:{game:React.RefObject<Game>;remaining:number;onEat:(now:number)=>void}){return <><color attach="background" args={['#b08162']}/><fog attach="fog" args={['#b08162',10,22]}/><ambientLight intensity={.38} color="#ffe0bb"/><hemisphereLight args={['#ffe7ca','#6f4a38',1.0]}/><directionalLight position={[-3,6,4]} intensity={3.05} color="#ffdfb9" castShadow shadow-mapSize={[2048,2048]} shadow-normalBias={.04} shadow-bias={-.00015} shadow-radius={5}/><directionalLight position={[3,4,-2]} intensity={1.2} color="#ffd2a0"/><directionalLight position={[1,3,5]} intensity={.42} color="#fff2da"/><directionalLight position={[-1.5,2.4,-4.5]} intensity={.55} color="#ffcf9e"/><RoomReflections/><Majlis/><Character id={1} position={[-2.02,.02,-.30]} angle={.78} game={game}/><Character id={2} position={[0,.02,-2.05]} angle={0} game={game}/><Character id={3} position={[2.02,.02,-.30]} angle={-.78} game={game}/><MansafPlatter remaining={remaining}/><PlayerHand game={game} onEat={onEat}/></>}
function App(){
 const game=useRef(initial()),[view,setView]=useState({...game.current}),[help,setHelp]=useState(false);
 const publish=()=>setView({...game.current,scores:[...game.current.scores],lokma:{...game.current.lokma}});
 const start=()=>{platterFood.reset();const now=performance.now();game.current={...initial(),phase:'playing',started:now,nextBots:[0,1,2].map(i=>now+wait(i))};setHelp(false);publish();};
 useEffect(()=>{let frame:number;const tick=()=>{const g=game.current,now=performance.now();if(g.phase==='playing'){g.time=Math.max(0,30-(now-g.started)/1000);if(g.time<=0)finish(g,'timer');else for(let i=0;i<3;i++)if(now>=g.nextBots[i]&&g.phase==='playing'){const amount=Math.min(g.remaining,i===0?2+Math.floor(Math.random()*2):i===1?2+Math.floor(Math.random()*4):4+Math.floor(Math.random()*2));const seat=botSeats[i],target=platterFood.target(seat[0],seat[1]);if(target){g.biteTargets[i+1]=[target.x,foodSurface(target.x,target.z,g.remaining).height+.13,target.z];platterFood.consume(seat[0],seat[1],amount);}g.remaining-=amount;g.scores[i+1]+=amount;g.eaten[i+1]+=amount;g.bites[i+1]=now;g.nextBots[i]=now+wait(i);if(g.remaining<=0)finish(g,'platter');}publish();}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);
 const eat=(now:number)=>{const g=game.current,l=g.lokma;if(g.phase!=='playing'||l.failed||l.rolls<4)return;if(now-g.started>=30000){g.time=0;finish(g,'timer');publish();return;}const amount=Math.min(g.remaining,Math.max(1,Math.round(l.amount))),points=Math.max(1,Math.round(lokmaScore(l,now)*amount/Math.max(1,Math.round(l.amount))));platterFood.consume(l.x,l.z,amount);g.remaining-=amount;g.eaten[0]+=amount;g.scores[0]+=points;g.bites[0]=now;g.feedback=`${l.rolls>6?'SQUISHED':points>=7?'PERFECT LOKMA':'SAHTEIN'}! +${points}${l.meat?' · LAMB BONUS':''}`;g.feedbackAt=now;if(g.remaining<=0)finish(g,'platter');publish();};
 const rankings=view.scores.map((score,id)=>({score,id})).sort((a,b)=>b.score-a.score),winners=rankings.filter(x=>x.score===rankings[0].score),now=performance.now();
 return <main className="game"><Canvas shadows camera={{position:[0,3.75,5.2],fov:36}} onCreated={({camera})=>camera.lookAt(0,.95,-.05)} dpr={[1,1.6]} gl={{toneMappingExposure:1.12}}><Scene game={game} remaining={view.remaining} onEat={eat}/></Canvas><div className="vignette"/>
 <header><div className="brand"><span className="brand-mark">♛</span><div><span>MANSAF</span><b>RUSH</b><small>EAT FAST. BE THE FIRST!</small></div></div><div className={'timer '+(view.time<10?'urgent':'')}><span className="clock">◷</span>00:{Math.ceil(view.time).toString().padStart(2,'0')}<small>SECONDS LEFT</small></div><div className="remaining"><div><span>Mansaf Left</span><strong>{view.remaining}<em>%</em></strong></div><div className="track"><i style={{width:`${view.remaining}%`}}/></div></div></header>
 {view.phase==='playing'&&<section className="hand-guide"><div className={'feedback '+(now-view.feedbackAt<1100?'show':'')}>{view.feedback}</div><b>{lokmaLabel(view.lokma)}</b><span>{view.lokma.amount.toFixed(1)} {view.lokma.bread>.05?(view.lokma.amount-view.lokma.bread>.05?'rice + shrak':'shrak'):'rice'} · {view.lokma.amount<3?'small':view.lokma.amount<=6.5?'ideal amount':'overflowing'}{view.lokma.meat?' · lamb included':''}</span><small>HOLD MOUSE + DRAG to gather · HOLD SPACE + alternate ← → to roll · ↑ to eat</small><small>{view.lokma.space?`Next: ${view.lokma.last==='ArrowLeft'?'→':'←'} · ${view.lokma.rolls} rolls (4–6 ideal)`:'Release mouse before forming your lokma'}</small></section>}
 <footer><div className="scoreboard">{NAMES.map((name,i)=><div className={'score '+(i===0?'you':'')} key={name} style={{'--accent':COLORS[i]} as React.CSSProperties}><div className="avatar"><Portrait id={i}/></div><div><span>{name}{i===0&&<small>YOU</small>}</span><strong>{view.scores[i]}<em> points</em></strong></div><span className="bot-style">{['YOUR SEAT','QUICK BITES','STEADY EATER','BIG APPETITE'][i]}</span></div>)}</div><div className="footer-note"><span>GATHER · ROLL · EAT</span><button onClick={()=>setHelp(!help)} aria-label="How to play">? <span>How to play</span></button></div></footer>
 {help&&<div className="help"><button onClick={()=>setHelp(false)} aria-label="Close help">×</button><b>One hand. One perfect lokma.</b><p>Hold the left mouse button and drag through rice or exposed shrak bread. Aim for 3–6 food. Release the mouse, hold SPACE, and alternate ← / → four to six times. Press ↑ to eat.</p><p>Too much rice spills; too many rolls squash it. Eating loose rice drops it back. Size, quality, speed, and lamb earn points. Everyone shares one platter. The round keeps going while this panel is open.</p></div>}
 {view.phase==='ready'&&<div className="overlay"><section className="modal intro"><span className="eyebrow">WELCOME TO THE MAJLIS</span><div className="ornament">✳</div><h1>Good food.<br/><i>Steady hands.</i></h1><p>One mansaf. Four hungry friends.<br/>Scoop, shape your lokma, and get your share.</p><div className="rules"><span><b>01</b> Gather rice & shrak</span><span><b>02</b> Roll & eat</span><span><b>03</b> Score the most</span></div><button className="primary" onClick={start}>LET’S EAT <span>↗</span></button><small>MOUSE TO SCOOP · SPACE + ← → TO ROLL · ↑ TO EAT</small></section></div>}
 {view.phase==='ended'&&<div className="overlay"><section className="modal results"><span className="eyebrow">{view.reason==='platter'?'EVERY LAST BITE.':'THE 30 SECONDS ARE UP.'}</span><h1>{view.reason==='platter'?'Mansaf is gone!':'Time’s up!'}</h1><p>{winners.length>1?`A shared victory: ${winners.map(x=>NAMES[x.id]).join(' & ')}`:rankings[0].id===0?'You made the best bites. Sahtein!':`${NAMES[rankings[0].id]} made the best bites. Sahtein!`}</p><div className="rankings">{rankings.map((r,i)=><div key={r.id}><span>{i===0?'♛':String(i+1).padStart(2,'0')}</span><b>{NAMES[r.id]}</b><strong>{r.score}<small> points</small></strong></div>)}</div><button className="primary" onClick={start}>PLAY AGAIN <span>↻</span></button><small>{100-view.remaining} / 100 EATEN · {view.time.toFixed(1)} SECONDS REMAINING</small></section></div>}
 </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
